### ISSUE TITLE
Is this production ready ?

### ISSUE THREAD

**Issue by Zehir** [tve/node-red-vue#1]
Hello,

Not really an issue but I was not able to contact you on Node-RED forum.

Is this package ready for use ?

I know there is some missing feature but I plan to rewrite my extension for node red 4.0 and I am using vue for other projects so it's was a good way to start

Thanks

**Comment by tve** [comment]
Yes but no. I used this in node-red-flexdash but given the recent developments around an 'official' dashboard I'm no longer interested in contributing to the node-red community and am ramping my use of node-red down. For this reason, while node-red-vue works I will not be supporting it. If you have questions I can try to answer them.

**Comment by Zehir** [comment]
Ok thanks
